### PR TITLE
adding new method to get list of elb, should be much faster if you ha…

### PR DESCRIPTION
**Pull request by zbintliff**
…ve a lot of elbs or instances

### CODE REVIEW

**Comment by cchaudier** [comment]
It's a great PR. I have use this code.
Thanks.

**Comment by tubaguy50035** [comment]
It doesn't look like the sample `deregister_from_elb.sh` even utilizes the supplied `get_elb_list`.  Can you give an example of how you changed your `deregister_from_elb.sh` and/or `common_functions.sh` to take advantage of this?

**Comment by zbintliff** [comment]
Oh I changed it on a branch in our enterprise github to actually utilize
it. The PR is just to provide a better get elb function that is constant
time. Sourcing the common_functions.sh and using the function in your own
implementation works.

**Comment by zbintliff** [comment]
If you look at the top of common_functions.should and see ELB_LIST ="". IN my own branch I made that the function call.

**Comment by tubaguy50035** [comment]
So it would end up being like this, correct? `ELB_LIST=$(get_elb_list_constant get_instance_id)`

**Comment by zbintliff** [comment]
@tubaguy50035  Sorry Didn't see your email until just not (and cant find the comment) but the code would look like this:
```bash
get_elb_list_constant "$(get_instance_id)"
ELB_LIST="$INSTANCE_ELBS"
```
Since the `INSTANCE_ELBS` is set and exported [here](https://github.com/awslabs/aws-codedeploy-samples/pull/17/files#diff-a6b6b2ae2199a57d1849b5b68115616aR389)

**Comment by iiro** [comment]
+1 

This is excellent stuff. Hopefully will get merged soon - as having a static entry in common_functions for list of ELBs does not just work for dynamic environments.

**Pull request merged**
